apiVersion: apps/v1
kind: Deployment
metadata:
  name: multilingual-number-to-text
  labels:
    app: multilingual-number-to-text
spec:
  replicas: 3
  selector:
    matchLabels:
      app: multilingual-number-to-text
  template:
    metadata:
      labels:
        app: multilingual-number-to-text
    spec:
      containers:
      - name: multilingual-number-to-text
        image: multilingual-number-to-text:latest
        imagePullPolicy: Never  # Forces use of local image
        ports:
        - containerPort: 8080
        command: ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8080"]
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"