apiVersion: v1
kind: Service
metadata:
  name: multilingual-number-to-text-service
spec:
  selector:
    app: multilingual-number-to-text
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP